version: "2.2"
services:
  redis:
    image: redis
    networks:
      - back-end
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - back-end
  vote:
    build: ./vote
    ports:
      - 5000:80
    depends_on:
      - redis
    networks:
      - back-end
  result:
    build: ./result
    ports:
      - 5001:80
    depends_on:
      - redis
      - db
    networks:
      - front-end
      - back-end
  worker:
    build: ./worker
    depends_on:
      - redis
      - db
    networks:
      - back-end
networks:
  front-end:
  back-end:
